/*
    Generated by Atomist on 06 07 2016 
*/
package com.example.vehicleInfo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class VehicleInfoApplication {

    public static void main(String[] args) {
        SpringApplication.run(VehicleInfoApplication.class, args);
    }
}
